export interface CountryCode {
  name: string;
  code: string;
  dial: string;
}

export const countryCodes: CountryCode[] = [
  { name: "United States", code: "US", dial: "+1" },
  { name: "United Kingdom", code: "GB", dial: "+44" },
  { name: "Canada", code: "CA", dial: "+1" },
  { name: "Australia", code: "AU", dial: "+61" },
  { name: "Germany", code: "DE", dial: "+49" },
  { name: "France", code: "FR", dial: "+33" },
  { name: "Italy", code: "IT", dial: "+39" },
  { name: "Spain", code: "ES", dial: "+34" },
  { name: "Netherlands", code: "NL", dial: "+31" },
  { name: "Belgium", code: "BE", dial: "+32" },
  { name: "Switzerland", code: "CH", dial: "+41" },
  { name: "Austria", code: "AT", dial: "+43" },
  { name: "Sweden", code: "SE", dial: "+46" },
  { name: "Norway", code: "NO", dial: "+47" },
  { name: "Denmark", code: "DK", dial: "+45" },
  { name: "Finland", code: "FI", dial: "+358" },
  { name: "Ireland", code: "IE", dial: "+353" },
  { name: "Portugal", code: "PT", dial: "+351" },
  { name: "New Zealand", code: "NZ", dial: "+64" },
  { name: "South Africa", code: "ZA", dial: "+27" },
  { name: "India", code: "IN", dial: "+91" },
  { name: "Brazil", code: "BR", dial: "+55" },
  { name: "Mexico", code: "MX", dial: "+52" },
  { name: "Japan", code: "JP", dial: "+81" },
  { name: "South Korea", code: "KR", dial: "+82" },
  { name: "China", code: "CN", dial: "+86" },
  { name: "Singapore", code: "SG", dial: "+65" },
  { name: "Hong Kong", code: "HK", dial: "+852" },
  { name: "UAE", code: "AE", dial: "+971" },
  { name: "Saudi Arabia", code: "SA", dial: "+966" },
  { name: "Israel", code: "IL", dial: "+972" },
  { name: "Turkey", code: "TR", dial: "+90" },
  { name: "Poland", code: "PL", dial: "+48" },
  { name: "Czech Republic", code: "CZ", dial: "+420" },
  { name: "Romania", code: "RO", dial: "+40" },
  { name: "Hungary", code: "HU", dial: "+36" },
  { name: "Greece", code: "GR", dial: "+30" },
  { name: "Argentina", code: "AR", dial: "+54" },
  { name: "Chile", code: "CL", dial: "+56" },
  { name: "Colombia", code: "CO", dial: "+57" },
  { name: "Philippines", code: "PH", dial: "+63" },
  { name: "Thailand", code: "TH", dial: "+66" },
  { name: "Malaysia", code: "MY", dial: "+60" },
  { name: "Indonesia", code: "ID", dial: "+62" },
  { name: "Vietnam", code: "VN", dial: "+84" },
  { name: "Egypt", code: "EG", dial: "+20" },
  { name: "Nigeria", code: "NG", dial: "+234" },
  { name: "Kenya", code: "KE", dial: "+254" },
  { name: "Pakistan", code: "PK", dial: "+92" },
  { name: "Bangladesh", code: "BD", dial: "+880" },
  { name: "Tunisia", code: "TN", dial: "+216" },
  { name: "Algeria", code: "DZ", dial: "+213" },
  { name: "Morocco", code: "MA", dial: "+212" },
  { name: "Libya", code: "LY", dial: "+218" },
  { name: "Lebanon", code: "LB", dial: "+961" },
  { name: "Jordan", code: "JO", dial: "+962" },
  { name: "Iraq", code: "IQ", dial: "+964" },
  { name: "Kuwait", code: "KW", dial: "+965" },
  { name: "Qatar", code: "QA", dial: "+974" },
  { name: "Bahrain", code: "BH", dial: "+973" },
  { name: "Oman", code: "OM", dial: "+968" },
];

export const defaultCountryCode = countryCodes[0]; // US +1
